name: Deploy to Azure Web App (Next.js)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"
  APP_NAME: "secondchanceplusapp"   # <-- Azure App Service name (NOT the long default domain)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (Next.js standalone)
        run: |
          npm run build
          # Package the minimal runtime produced by Next standalone output
          rm -rf package
          mkdir -p package
          cp -r .next/standalone/* package/
          mkdir -p package/.next
          cp -r .next/static package/.next/static || true
          # include public assets if any
          if [ -d "public" ]; then mkdir -p package/public && cp -r public/* package/public/; fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: package
